[build]
  command = "pnpm run build"
  publish = "dist/client"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/__tanstack-start"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200